### ISSUE TITLE
can't save preset

### ISSUE THREAD

**Issue by Rogal80** [Gerschel/sd_web_ui_preset_utils#2]
Hi, I can't save preset – button for safe is always gray 

![image](https://user-images.githubusercontent.com/112553453/208057362-535576c3-a32d-48a2-9bcb-c6b38fe5f6ab.png)

Windows, Firefox- WebUI latest

**Comment by Gerschel** [comment]
Currently, for some reason, the dropdown doesn't update when it circles around on itself. Give it a restart and see if it shows up.  If it doesn't, I have another bug. I'm going to put this as a more important milestone at this point.

**Comment by Gerschel** [comment]
I pushed an update that fixes the dropdown updating, and controls visibility of save button and resets name field.  
![image](https://user-images.githubusercontent.com/9631031/208215168-35bb9c18-86a9-41b0-b5db-346588320aa5.png)
![image](https://user-images.githubusercontent.com/9631031/208215203-b0dafade-d42c-4953-97ff-91a8623d13dd.png)

Do you still have this issue? I've tested the current one in firefox and chrome.

**Comment by Rogal80** [comment]
thx , its fixed :)

**Comment by Gerschel** [comment]
Can you check my post and give an opinion. https://github.com/Gerschel/sd_web_ui_preset_utils/discussions/29#discussioncomment-4704061
