### ISSUE TITLE
"width" and "heigth" presets not working with "stable-diffusion-webui-randomize" extension

### ISSUE THREAD

**Issue by hzielke** [Gerschel/sd_web_ui_preset_utils#22]
Pulling presets did not set "width" and "heigth", saving preset from either quick set or deteiled save did not save values.

Tracked down presence of extension "stable-diffusion-webui-randomize" as trigger.

**Comment by Gerschel** [comment]
I've been trying to figure out how to workaround this situation.  
This has been the bane to this entire project. No one want's to hand-off enough data. (It's making think about writing some guides.)

This is absolutely the cause.

What is happening, the other script uses the same Label of what is already being used, and did not implement a element id.  
So I have no way of distinguishing them at the moment.  So one component is overwriting the other in my mapping. 
This even happens to the default `Mask Blur` and the built-in extensions `Mask Blur`, same label, no element id.

I think the best I can do at this time, is set it to not overwrite the default ones if another script has the same parameter's.  
I'm going to think about this one for a moment.  
I've been digging through a1111's webui's code, trying to find the best spot to inject script metadata. I actually worked out how to make a preset manager that would work on all tabs, but it has to become a built-in to work cleanly.

A workaround would be, set the extensions you aren't going to use, to disabled by checking off the checkbox and clicking `Apply and restart ui`.  
Or.  
Go in to the conflicting extensions, and modify the `label` of the component so it's unique. Add a hyphen, underscore, extra space, something to make it different. 
![image](https://user-images.githubusercontent.com/9631031/209452484-5c9424f4-cd6a-4c02-a5d3-55db0f753768.png)
