### ISSUE TITLE
Checking for Updates in Extensions tab resets all user presets

### ISSUE THREAD

**Issue by Arindel** [Gerschel/sd_web_ui_preset_utils#25]
I would like for user presets to not be lost every time I check for updates in extensions tab.

**Comment by Gerschel** [comment]
https://github.com/Gerschel/sd_web_ui_preset_utils/issues/23

**Comment by Gerschel** [comment]
I'm sorry that happened. It should be resolved now. I wish I had a way to communicate to others to make a backup. The webui decided they wanted the extensions tab to do an overwrite.  
In the most recent update. I have included the logic in the main file (has to be main file too, can't be the install file), to write your presets to a different name and use those instead.

**Comment by Gerschel** [comment]
Can you check my post and give an opinion. https://github.com/Gerschel/sd_web_ui_preset_utils/discussions/29#discussioncomment-4704061
