### ISSUE TITLE
possible to move it to top at Quick Settings or bottom of the Image Gallery?

### ISSUE THREAD

**Issue by Gerschel** [Gerschel/sd_web_ui_preset_utils#27]
possible to move it to top at Quick Settings or bottom of the Image Gallery?

_Originally posted by @mocmocmoc in https://github.com/Gerschel/sd_web_ui_preset_utils/discussions/26#discussioncomment-4587954_

**Comment by Gerschel** [comment]
I just shoved it under the gallery, and pulled style rules that it was using to try to hold it's positon, which was making it not be sized correctly. It simplified the code, although leaves me with having to refactor.  

I included a javascript class where someone could toy around with it's location, the location won't stick on reload. I'm finding it difficult to find fire it onload after the shadowroot has loaded.  

I had tested it in quicksettings area. It causes two bugs. One bug is, it isn't in the tab when the tab gets hidden and the other becomes visible, so I would have to code the hiding and unhiding, which wouldn't be that hard.  

The second, and most damaging bug, the webui uses a javascript function `get_uiCurrentTab` to manage visible elements on the page. It set to target the first occurence of an element with the class `tabs`, which is an auto assigned class on any component using tabs. I just made a pull request with a fix for this.  
If the pull request is accepted, this will allow tabs in quicksettings, for cross tab features like a preset manager on all tabs.

**Comment by Gerschel** [comment]
If you are interested is seeing how it behaves. I wrote a script that moves it. It's included in the project. To run it.  Pop this in your console.
```javascript
let mover = new PresetManagerMover("txt2img_preset_manager_accordion", "quicksettings", "")
mover.move('beforebegin')
```
To move it back, update the target location.  Then move.
```javascript
mover.updateTarget('txt2img_generation_info_button')
mover.move('afterend')
```

**Comment by mocmocmoc** [comment]
> I just shoved it under the gallery, and pulled style rules that it was using to try to hold it's positon, which was making it not be sized correctly. It simplified the code, although leaves me with having to refactor.

Awesome! Seems to be working fine on my side.
[Unrelated] Just realized you also made sd-web-ui-quickcss extension. I love it 👍

**Comment by Gerschel** [comment]
I'm doing a fix. 
Highres. fix was renamed to Hires. fix, I'm almost done scripting the preset updater to change the name in users presets.
