### ISSUE TITLE
Current A1111 UI layout renamed "Sampling Steps" to "Sampling steps" (case change)

### ISSUE THREAD

**Issue by DoughyInTheMiddle** [Gerschel/sd_web_ui_preset_utils#28]
@Gerschel 

With the most recent UI changes to the layout of txt2img and img2img, the case of "steps" is no longer uppercase, "Steps", so the value doesn't get changed when clicking on the dropdown..

I am not well versed in GitHub, so I made the changes manually to the `zpreset_utils.py` and `presets.json`.

Will need to updated in the master.

**Comment by Gerschel** [comment]
There's another change you will need to do if you do it locally. I modified it in the code already. It might be easier to let the updater run.  
Everywhere that says "Sampling Steps" in your presets.json will need to be changed.  
I included it in the section that will run through the file and do it.  

Good catch.

**Comment by DoughyInTheMiddle** [comment]
Yeah, sorry, I meant to include that too, but had already made the change. 

Thanks for the quick turnaround!

**Comment by Gerschel** [comment]
https://github.com/Gerschel/sd_web_ui_preset_utils/discussions/29#discussioncomment-4704061
